version: "2"

tasks:
  test:kubeval:
    cmds:
      - kubeval --strict -d test/fixtures/pass

  test:kubectl:
    cmds:
      - kubectl apply --dry-run --validate -R -f test/fixtures/pass

  test:acceptance:
    cmds:
      - bats test/*_test.bats

  test:ci:
    cmds:
      - task: test:kubeval
      - task: test:kubectl
      - task: test:acceptance
