version: "1.0"
fail_fast: true
stages:
  - prepare
  - test

steps:
  clone:
    stage: prepare
    title: Clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    git: github

  build:
    stage: prepare
    title: Build step image
    type: build
    registry: utility
    working_directory: ${{clone}}
    dockerfile: codefresh/Dockerfile
    image_name: ${{CF_PIPELINE_NAME}}
    tag: ${{CF_REVISION}}
    disable_push: true

  test:
    stage: test
    title: Run tests
    image: ${{build}}
    working_directory: ${{clone}}
    commands:
      - bats test/secret_test.bats
    hooks:
      on_elected:
        exec:
          image: codefresh/kubectl
          commands:
            - kubectl config use-context skillshare-utility
