version: "1.0"
fail_fast: true
stages:
  - prepare
  - test
  - release

hooks:
  on_elected:
    fail_fast: true
    steps:
      set_kube_context:
        image: codefresh/kubectl
        commands:
          - kubectl config use-context skillshare-utility
steps:
  clone:
    stage: prepare
    title: Clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    git: github

  clone_submodules:
    stage: prepare
    title: Submodules
    working_directory: ${{clone}}
    # This includes git
    image: codefresh/cli
    commands:
      - git submodule update --init --recursive

  clone_blueprint_master:
    stage: prepare
    title: Clone blueprint
    type: git-clone
    repo: skillshare/blueprint
    revision: master
    git: github

  clone_blueprint_branch:
    stage: prepare
    title: Clone blueprint
    type: git-clone
    repo: skillshare/blueprint
    revision: ${{CF_BRANCH}}
    git: github

  build:
    stage: prepare
    title: Build
    type: build
    registry: utility
    working_directory: ${{clone}}
    image_name: conftest/kubernetes
    tag: ${{CF_REVISION}}
    disable_push: true

  test:
    stage: test
    title: Test policies
    image: ${{build}}
    working_directory: ${{clone}}
    commands:
      - task test:ci

  test_blueprint_branch:
    stage: test
    title: Test blueprint branch
    image: ${{build}}
    working_directory: ${{clone_blueprint_branch}}
    commands:
      - check-release sandbox
      - check-release staging
      - check-release prod
    when:
      steps:
        - name: clone_blueprint_branch
          on:
            - success

  test_blueprint_master:
    stage: test
    title: Test blueprint master
    image: ${{build}}
    working_directory: ${{clone_blueprint_master}}
    commands:
      - check-release sandbox
      - check-release staging
      - check-release prod
    when:
      steps:
        - name: clone_blueprint_master
          on:
            - success

  push:
    stage: release
    title: Push
    type: push
    candidate: ${{build}}
    registry: utility
    image_name: conftest/kubernetes
    tag: latest
    when:
      condition:
        all:
          executeForMasterBranch: "'${{CF_BRANCH}}' == 'master'"
