version: "1.0"
fail_fast: true
stages:
  - prepare
  - test

steps:
  clone:
    stage: prepare
    title: Clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    git: github

  detect_chart:
    stage: prepare
    title: Detect chart
    image: alpine:3.10
    working_directory: ${{clone}}
    commands:
      - test -f chart/Chart.yaml
      - test -f deploy/test/values.yaml

  test_releases:
    stage: test
    title: Check releases
    working_directory: ${{clone}}
    image: 289698421666.dkr.ecr.us-east-1.amazonaws.com/conftest/kubernetes:latest
    matrix:
      commands:
        - [check-release sandbox]
        - [check-release staging]
        - [check-release prod]
    when:
      steps:
        - name: detect_chart
          on:
            - success

  test_chart_values_schema:
    stage: test
    title: Check values JSON schema
    image: 289698421666.dkr.ecr.us-east-1.amazonaws.com/codefresh/shell
    working_directory: ${{clone}}
    commands:
      - test -f chart/values.schema.json
      - jq -re . chart/values.schema.json
    when:
      steps:
        - name: detect_chart
          on:
            - success
